### ISSUE TITLE
Section 2A. Exercise 1. Incorrect?

### ISSUE THREAD

**Issue by sampl0** [GaotangLi/Linear_Algebra_Done_Right_4th_ManualSolution#3]
Hey, thanks for uploading these solutions, I've found them very helpful as I work through the text.
I noticed an issue with the solution for Exercise 2A. Question 1.

**Issue**
The span of (1,0,0), (0,1,0), (0,0,1), (1,1,1) does not equal {(x,y,z) \in \mathbb{F}^3 : x+y+z = 0}.

The span of (1,0,0), (0,1,0), (0,0,1),(1,1,1) = \mathbb{F}^3.

However the set in the problem is a strict subset of F^3.

**A Solution**
One of the correct solutions is (1,0,-1),  (0,-1,1),  (1,-1,0), (1,-2,1)

The span of (1,0,-1), (1,-1,0) = {(x,y,z) \in \mathbb{F}^3 : x+y+z = 0}

Since (1,-1,0) and (1,-2,1) are linear combinations of (1,0,-1), (1,-1,0) they do not change the span.

**Comment by GaotangLi** [comment]
Thank you so much! You are right, the correct solution will be updated.
